package Telas;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import Processamento.Processamento_Imagem_;


/**
 * @author João Victor do Rozário Recla - 2022/2
 */
public class Tela_Principal_ extends javax.swing.JFrame {
    
    public File Img_original;
    public boolean Img_carregada;
    public BufferedImage Img_atual;
    public BufferedImage Img_processada_atual;
    public BufferedImage Img_final_atual;
    public File Caminho = new File("/home/");
    public boolean Img_YCbCr, Img_XYZ, Img_segmentada;
    public boolean Img_Gamma, Img_C;
    
    /**
     * Creates new form TelaPrincipal
     */
    public Tela_Principal_() {
//        initComponents();
        initComponents2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents2() {
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        Menus = new javax.swing.JMenuBar();
        Menu_Arquivo_ = new javax.swing.JMenu();
        Carregar_Imagem_ = new javax.swing.JMenuItem();
        ___Separador_01 = new javax.swing.JPopupMenu.Separator();
        Salvar_ = new javax.swing.JMenuItem();
        ___Separador_03 = new javax.swing.JPopupMenu.Separator();
        Sair_ = new javax.swing.JMenuItem();
        Menu_Skin_Detection_ = new javax.swing.JMenu();
        Menu_Gamma_YIQ_ = new javax.swing.JMenu();
        Aplicar_Imagem_ = new javax.swing.JMenuItem();
        Aplicar_Gamma_Imagem_ = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Aplicar_Lote_ = new javax.swing.JMenuItem();
        Aplicar_Gamma_Lote_ = new javax.swing.JMenuItem();
        Menu_Segmentacao_ = new javax.swing.JMenu();
        Binarizacao_Otsu_ = new javax.swing.JMenu();
        Aplicar_Otsu_Imagem_ = new javax.swing.JMenuItem();
        ___Separador_07 = new javax.swing.JPopupMenu.Separator();
        Aplicar_Otsu_Lote_ = new javax.swing.JMenuItem();
        ___Separador_04 = new javax.swing.JPopupMenu.Separator();
        Binarizacao_Fuzzy_Huang_ = new javax.swing.JMenu();
        Aplicar_FuzzyHuang_Imagem_ = new javax.swing.JMenuItem();
        ___Separador_08 = new javax.swing.JPopupMenu.Separator();
        Aplicar_FuzzyHuang_Lote_ = new javax.swing.JMenuItem();
        Menu_Outros_ = new javax.swing.JMenu();
        Sobre_ = new javax.swing.JMenuItem();
        
        jMenu4.setText("jMenu4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem12.setText("jMenuItem12");

        jMenuItem14.setText("jMenuItem14");

        jMenuItem15.setText("jMenuItem15");
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Detecção de pele humana em imagens - Lucas Sala Alves");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);
        setLocation(new java.awt.Point(0, 0));
        
        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );
        
        Menus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Menus.setAlignmentY(0.5F);
        Menus.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Menus.setMargin(new java.awt.Insets(20, 20, 20, 20));
        Menus.setMaximumSize(new java.awt.Dimension(479, 32775));
        Menus.setPreferredSize(new java.awt.Dimension(480, 35));
        
        Menu_Arquivo_.setBorder(null);
        Menu_Arquivo_.setText("Arquivo");
        Menu_Arquivo_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Menu_Arquivo_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Menu_Arquivo_.setPreferredSize(new java.awt.Dimension(70, 25));
        
        Carregar_Imagem_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Carregar_Imagem_.setText("Carregar imagem");
        Carregar_Imagem_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Carregar_Imagem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carregar_Imagem_ActionPerformed(evt);
            }
        });
        Menu_Arquivo_.add(Carregar_Imagem_);
        Menu_Arquivo_.add(___Separador_01);
        
        Salvar_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Salvar_.setText("Salvar");
        Salvar_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Salvar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar_ActionPerformed(evt);
            }
        });
        Menu_Arquivo_.add(Salvar_);
        Menu_Arquivo_.add(___Separador_03);
        
        Sair_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Sair_.setText("Sair");
        Sair_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair_ActionPerformed(evt);
            }
        });
        Menu_Arquivo_.add(Sair_);

        Menus.add(Menu_Arquivo_);
        
        Menu_Gamma_YIQ_.setBorder(null);
        Menu_Gamma_YIQ_.setText("Gamma YIQ");
        Menu_Gamma_YIQ_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Menu_Gamma_YIQ_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Menu_Gamma_YIQ_.setPreferredSize(new java.awt.Dimension(120, 25));

        Aplicar_Gamma_Imagem_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_Gamma_Imagem_.setText("Aplicar na Imagem");
        Aplicar_Gamma_Imagem_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Aplicar_Gamma_Imagem_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_Gamma_Imagem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_Gamma_Imagem_ActionPerformed(evt);
            }
        });
        Menu_Gamma_YIQ_.add(Aplicar_Gamma_Imagem_);
        Menu_Gamma_YIQ_.add(jSeparator2);
        
        Aplicar_Gamma_Lote_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_Gamma_Lote_.setText("Aplicar em Lote");
        Aplicar_Gamma_Lote_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Aplicar_Gamma_Lote_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_Lote_ActionPerformed(evt);
            }
        });
        Menu_Gamma_YIQ_.add(Aplicar_Gamma_Lote_);

        Menus.add(Menu_Gamma_YIQ_);
        
        Menu_Skin_Detection_.setBorder(null);
        Menu_Skin_Detection_.setText("Skin Detection");
        Menu_Skin_Detection_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Menu_Skin_Detection_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Menu_Skin_Detection_.setPreferredSize(new java.awt.Dimension(120, 25));

        Aplicar_Imagem_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_Imagem_.setText("Aplicar na Imagem");
        Aplicar_Imagem_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Aplicar_Imagem_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_Imagem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_Imagem_ActionPerformed(evt);
            }
        });
        Menu_Skin_Detection_.add(Aplicar_Imagem_);
        Menu_Skin_Detection_.add(jSeparator1);
        
        Aplicar_Lote_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_Lote_.setText("Aplicar em Lote");
        Aplicar_Lote_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Aplicar_Lote_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_Lote_ActionPerformed(evt);
            }
        });
        Menu_Skin_Detection_.add(Aplicar_Lote_);

        Menus.add(Menu_Skin_Detection_);
        
        Menu_Segmentacao_.setBorder(null);
        Menu_Segmentacao_.setText("Segmentação");
        Menu_Segmentacao_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Menu_Segmentacao_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Menu_Segmentacao_.setMaximumSize(new java.awt.Dimension(115, 32767));

        Binarizacao_Otsu_.setBorder(null);
        Binarizacao_Otsu_.setText("Binarização de Otsu");
        Binarizacao_Otsu_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Binarizacao_Otsu_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Binarizacao_Otsu_.setPreferredSize(new java.awt.Dimension(170, 25));

        Aplicar_Otsu_Imagem_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_Otsu_Imagem_.setText("Aplicar na imagem");
        Aplicar_Otsu_Imagem_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Aplicar_Otsu_Imagem_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_Otsu_Imagem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_Otsu_Imagem_ActionPerformed(evt);
            }
        });
        Binarizacao_Otsu_.add(Aplicar_Otsu_Imagem_);
        Binarizacao_Otsu_.add(___Separador_07);
        
        Binarizacao_Fuzzy_Huang_.setBorder(null);
        Binarizacao_Fuzzy_Huang_.setText("Bin Fuzzy de Huang");
        Binarizacao_Fuzzy_Huang_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Binarizacao_Fuzzy_Huang_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Binarizacao_Fuzzy_Huang_.setPreferredSize(new java.awt.Dimension(170, 25));

        Aplicar_FuzzyHuang_Imagem_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_FuzzyHuang_Imagem_.setText("Aplicar na imagem");
        Aplicar_FuzzyHuang_Imagem_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Aplicar_FuzzyHuang_Imagem_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_FuzzyHuang_Imagem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_FuzzyHuang_Imagem_ActionPerformed(evt);
            }
        });
        Binarizacao_Fuzzy_Huang_.add(Aplicar_FuzzyHuang_Imagem_);
        Binarizacao_Fuzzy_Huang_.add(___Separador_08);

        Aplicar_FuzzyHuang_Lote_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_FuzzyHuang_Lote_.setText("Aplicar em lote");
        Aplicar_FuzzyHuang_Lote_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Aplicar_FuzzyHuang_Lote_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_FuzzyHuang_Lote_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_FuzzyHuang_Lote_ActionPerformed(evt);
            }
        });
        Binarizacao_Fuzzy_Huang_.add(Aplicar_FuzzyHuang_Lote_);

        Menu_Segmentacao_.add(Binarizacao_Fuzzy_Huang_);

        Menus.add(Menu_Segmentacao_);
        
        Menu_Outros_.setBorder(null);
        Menu_Outros_.setText("Outros");
        Menu_Outros_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Menu_Outros_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Menu_Outros_.setPreferredSize(new java.awt.Dimension(60, 25));

        Sobre_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Sobre_.setText("Sobre o software");
        Sobre_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Sobre_.setPreferredSize(new java.awt.Dimension(170, 25));
        Sobre_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sobre_ActionPerformed(evt);
            }
        });
        Menu_Outros_.add(Sobre_);

        Menus.add(Menu_Outros_);

        setJMenuBar(Menus);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        Menus = new javax.swing.JMenuBar();
        Menu_Arquivo_ = new javax.swing.JMenu();
        Carregar_Imagem_ = new javax.swing.JMenuItem();
        ___Separador_01 = new javax.swing.JPopupMenu.Separator();
        Salvar_ = new javax.swing.JMenuItem();
        ___Separador_03 = new javax.swing.JPopupMenu.Separator();
        Sair_ = new javax.swing.JMenuItem();
        Menu_Skin_Detection_ = new javax.swing.JMenu();
        Aplicar_Imagem_ = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Aplicar_Lote_ = new javax.swing.JMenuItem();
        Menu_Segmentacao_ = new javax.swing.JMenu();
        Binarizacao_Otsu_ = new javax.swing.JMenu();
        Aplicar_Otsu_Imagem_ = new javax.swing.JMenuItem();
        ___Separador_07 = new javax.swing.JPopupMenu.Separator();
        Aplicar_Otsu_Lote_ = new javax.swing.JMenuItem();
        ___Separador_04 = new javax.swing.JPopupMenu.Separator();
        Binarizacao_Fuzzy_Huang_ = new javax.swing.JMenu();
        Aplicar_FuzzyHuang_Imagem_ = new javax.swing.JMenuItem();
        ___Separador_08 = new javax.swing.JPopupMenu.Separator();
        Aplicar_FuzzyHuang_Lote_ = new javax.swing.JMenuItem();
        Menu_Outros_ = new javax.swing.JMenu();
        Sobre_ = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem12.setText("jMenuItem12");

        jMenuItem14.setText("jMenuItem14");

        jMenuItem15.setText("jMenuItem15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Detecção de pele humana em imagens - Lucas Sala Alves");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);
        setLocation(new java.awt.Point(0, 0));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        Menus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Menus.setAlignmentY(0.5F);
        Menus.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Menus.setMargin(new java.awt.Insets(20, 20, 20, 20));
        Menus.setMaximumSize(new java.awt.Dimension(479, 32775));
        Menus.setPreferredSize(new java.awt.Dimension(480, 35));

        Menu_Arquivo_.setBorder(null);
        Menu_Arquivo_.setText("Arquivo");
        Menu_Arquivo_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Menu_Arquivo_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Menu_Arquivo_.setPreferredSize(new java.awt.Dimension(70, 25));

        Carregar_Imagem_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Carregar_Imagem_.setText("Carregar imagem");
        Carregar_Imagem_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Carregar_Imagem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carregar_Imagem_ActionPerformed(evt);
            }
        });
        Menu_Arquivo_.add(Carregar_Imagem_);
        Menu_Arquivo_.add(___Separador_01);

        Salvar_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Salvar_.setText("Salvar");
        Salvar_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Salvar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar_ActionPerformed(evt);
            }
        });
        Menu_Arquivo_.add(Salvar_);
        Menu_Arquivo_.add(___Separador_03);

        Sair_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Sair_.setText("Sair");
        Sair_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair_ActionPerformed(evt);
            }
        });
        Menu_Arquivo_.add(Sair_);

        Menus.add(Menu_Arquivo_);

        Menu_Skin_Detection_.setBorder(null);
        Menu_Skin_Detection_.setText("Skin Detection");
        Menu_Skin_Detection_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Menu_Skin_Detection_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Menu_Skin_Detection_.setPreferredSize(new java.awt.Dimension(120, 25));

        Aplicar_Imagem_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_Imagem_.setText("Aplicar na Imagem");
        Aplicar_Imagem_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Aplicar_Imagem_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_Imagem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_Imagem_ActionPerformed(evt);
            }
        });
        Menu_Skin_Detection_.add(Aplicar_Imagem_);
        Menu_Skin_Detection_.add(jSeparator1);

        Aplicar_Lote_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_Lote_.setText("Aplicar em Lote");
        Aplicar_Lote_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Aplicar_Lote_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_Lote_ActionPerformed(evt);
            }
        });
        Menu_Skin_Detection_.add(Aplicar_Lote_);

        Menus.add(Menu_Skin_Detection_);

        Menu_Segmentacao_.setBorder(null);
        Menu_Segmentacao_.setText("Segmentação");
        Menu_Segmentacao_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Menu_Segmentacao_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Menu_Segmentacao_.setMaximumSize(new java.awt.Dimension(115, 32767));

        Binarizacao_Otsu_.setBorder(null);
        Binarizacao_Otsu_.setText("Binarização de Otsu");
        Binarizacao_Otsu_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Binarizacao_Otsu_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Binarizacao_Otsu_.setPreferredSize(new java.awt.Dimension(170, 25));

        Aplicar_Otsu_Imagem_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_Otsu_Imagem_.setText("Aplicar na imagem");
        Aplicar_Otsu_Imagem_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Aplicar_Otsu_Imagem_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_Otsu_Imagem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_Otsu_Imagem_ActionPerformed(evt);
            }
        });
        Binarizacao_Otsu_.add(Aplicar_Otsu_Imagem_);
        Binarizacao_Otsu_.add(___Separador_07);

        Aplicar_Otsu_Lote_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_Otsu_Lote_.setText("Aplicar em lote");
        Aplicar_Otsu_Lote_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Aplicar_Otsu_Lote_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_Otsu_Lote_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_Otsu_Lote_ActionPerformed(evt);
            }
        });
        Binarizacao_Otsu_.add(Aplicar_Otsu_Lote_);

        Menu_Segmentacao_.add(Binarizacao_Otsu_);
        Menu_Segmentacao_.add(___Separador_04);

        Binarizacao_Fuzzy_Huang_.setBorder(null);
        Binarizacao_Fuzzy_Huang_.setText("Bin Fuzzy de Huang");
        Binarizacao_Fuzzy_Huang_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Binarizacao_Fuzzy_Huang_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Binarizacao_Fuzzy_Huang_.setPreferredSize(new java.awt.Dimension(170, 25));

        Aplicar_FuzzyHuang_Imagem_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_FuzzyHuang_Imagem_.setText("Aplicar na imagem");
        Aplicar_FuzzyHuang_Imagem_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Aplicar_FuzzyHuang_Imagem_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_FuzzyHuang_Imagem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_FuzzyHuang_Imagem_ActionPerformed(evt);
            }
        });
        Binarizacao_Fuzzy_Huang_.add(Aplicar_FuzzyHuang_Imagem_);
        Binarizacao_Fuzzy_Huang_.add(___Separador_08);

        Aplicar_FuzzyHuang_Lote_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_FuzzyHuang_Lote_.setText("Aplicar em lote");
        Aplicar_FuzzyHuang_Lote_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Aplicar_FuzzyHuang_Lote_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_FuzzyHuang_Lote_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_FuzzyHuang_Lote_ActionPerformed(evt);
            }
        });
        Binarizacao_Fuzzy_Huang_.add(Aplicar_FuzzyHuang_Lote_);

        Menu_Segmentacao_.add(Binarizacao_Fuzzy_Huang_);

        Menus.add(Menu_Segmentacao_);

        Menu_Outros_.setBorder(null);
        Menu_Outros_.setText("Outros");
        Menu_Outros_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Menu_Outros_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Menu_Outros_.setPreferredSize(new java.awt.Dimension(60, 25));

        Sobre_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Sobre_.setText("Sobre o software");
        Sobre_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Sobre_.setPreferredSize(new java.awt.Dimension(170, 25));
        Sobre_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sobre_ActionPerformed(evt);
            }
        });
        Menu_Outros_.add(Sobre_);

        Menus.add(Menu_Outros_);

        setJMenuBar(Menus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /*  Metodo para carregar uma imagem para o sistema. */
    private void Carregar_Imagem_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carregar_Imagem_ActionPerformed

        // Configura e abre uma janela de dialogo.
        JFileChooser Fs = new JFileChooser(Caminho);
        Fs.setFileFilter(new FileNameExtensionFilter("Arquivos de Imagem (png, jpg, jpeg, bmp)", "png", "jpg", "jpeg", "bmp"));
        Fs.setAcceptAllFileFilterUsed(false);
        Fs.setDialogTitle("Selecione um arquivo de imagem...");
        int Retorno = Fs.showOpenDialog(this);
        
        // Seleciona a imagem.
        if(Retorno == JFileChooser.APPROVE_OPTION){
            
            try {
                
                // Carrega a imagem para o sistema.
                Img_original = Fs.getSelectedFile();
                Img_atual    = ImageIO.read(Img_original);

                JLabel imageLabel = new JLabel();
                imageLabel.setIcon(new javax.swing.ImageIcon(Img_atual));
                
                JScrollPane scrollPane = new JScrollPane(imageLabel);
                
                JInternalFrame novaJanela = new JInternalFrame("Imagem Original", true,true,true,true);
                novaJanela.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
                novaJanela.setSize(Img_atual.getWidth(), Img_atual.getHeight());
                novaJanela.getContentPane().add(scrollPane);
                novaJanela.setVisible(true);
                
                jDesktopPane1.add(novaJanela);
                jDesktopPane1.setLayer(novaJanela, javax.swing.JLayeredPane.DEFAULT_LAYER,0);

                Img_carregada = true;
                Img_final_atual = Img_atual;
                // Atualiza o caminho com o diretorio da pasta selecionada.
                Caminho = Fs.getCurrentDirectory();
            } catch (IOException ex) {
                Logger.getLogger(Tela_Principal_.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Carregar_Imagem_ActionPerformed

    
    /*  Metodo para salvar uma imagem.  */
    private void Salvar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar_ActionPerformed
        
        JFrame F = new JFrame();
        
        if(Img_carregada){
            
            // Configura e abre uma janela de dialogo.
            JFileChooser Fs = new JFileChooser(new File(Img_original.getParent()));
            Fs.setFileFilter(new FileNameExtensionFilter("PNG Images", "png"));
            Fs.setDialogTitle("Escolha onde salvar a imagem processada...");
            int Retorno = Fs.showSaveDialog(this);

            // Seleciona a pasta.
            if(Retorno == JFileChooser.APPROVE_OPTION){
                
                File Fo = new File(Fs.getSelectedFile().getPath() + "_" +(Img_YCbCr ? "YCbCr" : "") + (Img_XYZ ? "XYZ" : "") + (Img_segmentada ? "_Segmentacao" : "") + ".png");
                
                try {
                    
                    ImageIO.write(Img_final_atual, "png", Fo);
                    Img_YCbCr = Img_XYZ = Img_segmentada = false;
                    JOptionPane.showMessageDialog(F, "Imagem salva com sucesso.");
                } catch (IOException ex) {
                    
                    JOptionPane.showMessageDialog(F, "Não foi possível salvar a imagem!");
                    Logger.getLogger(Tela_Principal_.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        }
    }//GEN-LAST:event_Salvar_ActionPerformed
     
    
    /*  Metodo para exibir as informacoes sobre o software. */
    private void Sobre_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sobre_ActionPerformed
        
        JFrame F = new JFrame();
        JOptionPane.showMessageDialog(F, "Programa desenvolvido e implementado por Lucas Sala Alves"
                                       + "\nem 2025/1, na disciplina de Processamento Digital de Imagens"
                                       + "\nministrada pelo Prof. Jacques Facon.");
    }//GEN-LAST:event_Sobre_ActionPerformed

    
    /*  Metodo para sair do sistema.    */
    private void Sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair_ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Sair_ActionPerformed


    private void Aplicar_Imagem_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_Imagem_ActionPerformed
        Tela_Espaco_cor Tela = new Tela_Espaco_cor(this,false);
        Tela.setLocationRelativeTo(null);
        Tela.setVisible(true);
        Img_YCbCr = false;
        Img_XYZ = false;
    }//GEN-LAST:event_Aplicar_Imagem_ActionPerformed
    
    private void Aplicar_Gamma_Imagem_ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        Tela_Gamma_YIQ Tela = new Tela_Gamma_YIQ(this, false);
        Tela.setLocationRelativeTo(null);
        Tela.setVisible(true);
        Img_Gamma = false;
        Img_C = false;
    }    
    
    public void Aplicar_GammaCorrectionYIQ_Imagem(Tela_Gamma_YIQ Tela){
        javax.swing.JDialog F = new javax.swing.JDialog();
         System.out.println("cheguei no aplica gamma correction");
        if(Img_carregada){
            System.out.println("passei do if img carregada");
            try{
                
                // Aplica o algoritmo na copia da imagem atual.
                BufferedImage Img_processada = Processamento_Imagem_.CriaCopia(Img_atual);
                Img_processada = Processamento_Imagem_.Gamma_YIQ(Img_processada, Tela);
                Img_Gamma = true;
                Img_C = true;
                Img_processada_atual = Img_processada;
                System.out.println("img processada atual = img processada");
                if(Img_processada_atual == null) {

                    JOptionPane.showMessageDialog(F, "Não foi possível aplicar a correção Gamma!");
                }else{

                       // ---------- NOVA JANELA COM A IMAGEM PROCESSADA ----------                                  
                    JLabel imageLabel = new JLabel();
                    imageLabel.setIcon(new javax.swing.ImageIcon(Img_processada));

                    JScrollPane scrollPane = new JScrollPane(imageLabel);

                    JInternalFrame novaJanela =
                            new JInternalFrame(
                                "Imagem Processada - Gamma YIQ",
                                true,
                                true,
                                true,
                                true
                        );
                    novaJanela.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
                    novaJanela.setSize(Img_processada.getWidth(), Img_processada.getHeight());
                    novaJanela.getContentPane().add(scrollPane);
                    novaJanela.setVisible(true);
                    
                    jDesktopPane1.add(novaJanela);
                    jDesktopPane1.setLayer(novaJanela, javax.swing.JLayeredPane.DEFAULT_LAYER,0);
                   
                    Img_final_atual = Img_processada;                    
                }
            }catch( NullPointerException | IllegalArgumentException ex){

                JOptionPane.showMessageDialog(F, "Não foi possível aplicar a correção Gamma!");
                Logger.getLogger(Tela_Principal_.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        }
        
    }
    
    public void Aplicar_SkinDetection_Imagem(Tela_Espaco_cor Tela){
        
        javax.swing.JDialog F = new javax.swing.JDialog();

        if(Img_carregada){
            
            try{
                
                // Aplica o algoritmo na copia da imagem atual.
                BufferedImage Img_processada = Processamento_Imagem_.CriaCopia(Img_atual);
                if(Tela.Ymin.isEnabled() || Tela.Cbmin.isEnabled() || Tela.Crmin.isEnabled()){
                    Img_processada = Processamento_Imagem_.YCbCr(Img_processada, Tela);
                    Img_YCbCr = true;
                }
                if(Tela.Xmin.isEnabled() || Tela.Yxyzmin.isEnabled() || Tela.Zmin.isEnabled()){
                    Img_processada = Processamento_Imagem_.XYZ(Img_processada, Tela);
                    Img_XYZ = true;
                }
                
                Img_processada_atual = Img_processada;
                
                if(Img_processada_atual == null) {

                    JOptionPane.showMessageDialog(F, "Não foi possível aplicar a deteccao de pele!");
                }else{

                       // ---------- NOVA JANELA COM A IMAGEM PROCESSADA ----------                                  
                    JLabel imageLabel = new JLabel();
                    imageLabel.setIcon(new javax.swing.ImageIcon(Img_processada));

                    JScrollPane scrollPane = new JScrollPane(imageLabel);

                    JInternalFrame novaJanela = new JInternalFrame("Imagem Processada" + 
                        (Img_YCbCr ? " YCbCr [" : "")+
                        (Tela.Ymin.isEnabled() ? "Y" : "")+(Tela.Cbmin.isEnabled() ? "Cb" : "")+(Tela.Crmin.isEnabled() ? "Cr" : "")
                         + (Img_YCbCr&&Img_XYZ ? "] e" : "") + (Img_XYZ ? " XYZ [" : "")+
                        (Tela.Xmin.isEnabled() ? "X" : "")+(Tela.Yxyzmin.isEnabled() ? "Y" : "")+(Tela.Zmin.isEnabled() ? "Z" : "")
                            +("]"),true,true,true,true);
                    novaJanela.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
                    novaJanela.setSize(Img_processada.getWidth(), Img_processada.getHeight());
                    novaJanela.getContentPane().add(scrollPane);
                    novaJanela.setVisible(true);
                    
                    jDesktopPane1.add(novaJanela);
                    jDesktopPane1.setLayer(novaJanela, javax.swing.JLayeredPane.DEFAULT_LAYER,0);
                   
                    Img_final_atual = Img_processada;                    
                }
            }catch( NullPointerException | IllegalArgumentException ex){

                JOptionPane.showMessageDialog(F, "Não foi possível aplicar a deteccao de pele!");
                Logger.getLogger(Tela_Principal_.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        }
    }
    
    
    /*  Metodo para aplicar o algoritmo de segmentacao
        "Binarizacao Otsu" em uma imagem.   */
    private void Aplicar_Otsu_Imagem_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_Otsu_Imagem_ActionPerformed
        
        JFrame F = new JFrame();
        
        if(Img_carregada){
            
            try{
                
                // Aplica o algoritmo na imagem atual.
                BufferedImage Img_processada = Processamento_Imagem_.Segment_(Img_processada_atual, 1);
                
                if(Img_processada == null) {
                    JOptionPane.showMessageDialog(F, "Não foi possível aplicar a segmentação!");
                }else{
                    JLabel imageLabel = new JLabel();
                    imageLabel.setIcon(new javax.swing.ImageIcon(Img_processada));

                    JScrollPane scrollPane = new JScrollPane(imageLabel);

                    JInternalFrame novaJanela = new JInternalFrame("Imagem Segmentada [Otsu]", true,true,true,true);
                    novaJanela.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
                    novaJanela.setSize(Img_processada.getWidth(), Img_processada.getHeight());
                    novaJanela.getContentPane().add(scrollPane);
                    novaJanela.setVisible(true);

                    jDesktopPane1.add(novaJanela);
                    jDesktopPane1.setLayer(novaJanela, javax.swing.JLayeredPane.DEFAULT_LAYER,0);
                    Img_segmentada = true;
                    Img_final_atual = Img_processada;
                }
            }catch( NullPointerException | IllegalArgumentException ex){
                
                JOptionPane.showMessageDialog(F, "Não foi possível aplicar a segmentação!");
                Logger.getLogger(Tela_Principal_.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        }
    }//GEN-LAST:event_Aplicar_Otsu_Imagem_ActionPerformed


    /*  Metodo para aplicar o algoritmo de segmentacao
        "Binarizacao Fuzzy Huang" em uma imagem.    */
    private void Aplicar_FuzzyHuang_Imagem_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_FuzzyHuang_Imagem_ActionPerformed
        
        JFrame F = new JFrame();
        
        if(Img_carregada){
            
            try{
                
                // Aplica o algoritmo na imagem atual.
                BufferedImage Img_processada = Processamento_Imagem_.Segment_(Img_processada_atual, 2);
                
                if(Img_processada == null) {
                    JOptionPane.showMessageDialog(F, "Não foi possível aplicar a segmentação!");
                }else{
                    JLabel imageLabel = new JLabel();
                    imageLabel.setIcon(new javax.swing.ImageIcon(Img_processada));

                    JScrollPane scrollPane = new JScrollPane(imageLabel);

                    JInternalFrame novaJanela = new JInternalFrame("Imagem Segmentada [Fuzzy]", true,true,true,true);
                    novaJanela.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
                    novaJanela.setSize(Img_processada.getWidth(), Img_processada.getHeight());
                    novaJanela.getContentPane().add(scrollPane);
                    novaJanela.setVisible(true);

                    jDesktopPane1.add(novaJanela);
                    jDesktopPane1.setLayer(novaJanela, javax.swing.JLayeredPane.DEFAULT_LAYER,0);
                    Img_segmentada = true;
                    Img_final_atual = Img_processada;
                }
            }catch(NullPointerException | IllegalArgumentException ex){
                
                JOptionPane.showMessageDialog(F, "Não foi possível aplicar a segmentação!");
                Logger.getLogger(Tela_Principal_.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        }
    }//GEN-LAST:event_Aplicar_FuzzyHuang_Imagem_ActionPerformed


    private void Aplicar_Lote_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_Lote_ActionPerformed
        Tela_Espaco_cor Tela = new Tela_Espaco_cor(this,true);
        Tela.setLocationRelativeTo(null);
        Tela.setVisible(true);
    }//GEN-LAST:event_Aplicar_Lote_ActionPerformed


    public void Aplicar_SkinDetection_Lote(Tela_Espaco_cor TelaCor) {
        Tela_Aplicacao_Lote_ Tela = new Tela_Aplicacao_Lote_(TelaCor);
        Tela.setLocationRelativeTo(null);
        if(TelaCor.Deteccao_tipo == 0) Tela.Metodo_nome = "_YCbCrXYZ";
        else Tela.Metodo_nome = (TelaCor.Deteccao_tipo == 1 ? "_YCbCr" : "_XYZ");
        Tela.setVisible(true);   
    }
    
    public void Aplicar_GammaCorrectionYIQ_Lote(Tela_Gamma_YIQ TelaCor) {
        Tela_Aplicacao_Lote_ Tela = new Tela_Aplicacao_Lote_(TelaCor);
        Tela.setLocationRelativeTo(null);
        Tela.Metodo_nome = "_GammaYIQ";
        Tela.setVisible(true);   
    }
    
    
    /*  Metodo para aplicar o algoritmo de segmentacao
        "Binarizacao Otsu" em um lote de imagens.   */
    private void Aplicar_Otsu_Lote_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_Otsu_Lote_ActionPerformed
        Tela_Aplicacao_Lote_ Tela = new Tela_Aplicacao_Lote_();
        Tela.setLocationRelativeTo(null);
        Tela.Metodo_nome         = "_Otsu";
        Tela.Segmentacao_tipo    = 1;
        Tela.setVisible(true);
    }//GEN-LAST:event_Aplicar_Otsu_Lote_ActionPerformed


    /*  Metodo para aplicar o algoritmo de segmentacao
        "Binarizacao Fuzzy Huang" em um lote de imagens.    */
    private void Aplicar_FuzzyHuang_Lote_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_FuzzyHuang_Lote_ActionPerformed
        Tela_Aplicacao_Lote_ Tela = new Tela_Aplicacao_Lote_();
        Tela.setLocationRelativeTo(null);
        Tela.Metodo_nome         = "_FuzzyHuang";
        Tela.Segmentacao_tipo    = 2;
        Tela.setVisible(true);
    }//GEN-LAST:event_Aplicar_FuzzyHuang_Lote_ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Tela_Principal_ telaPrincipal = new Tela_Principal_();
            telaPrincipal.setLocationRelativeTo(null);
            telaPrincipal.setExtendedState(JFrame.MAXIMIZED_BOTH);
            telaPrincipal.setVisible(true);
        });
        
        
    }

    private javax.swing.JMenu Menu_Gamma_YIQ_;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem Aplicar_Gamma_Imagem_;
    private javax.swing.JMenuItem Aplicar_Gamma_Lote_;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Aplicar_FuzzyHuang_Imagem_;
    private javax.swing.JMenuItem Aplicar_FuzzyHuang_Lote_;
    private javax.swing.JMenuItem Aplicar_Imagem_;
    private javax.swing.JMenuItem Aplicar_Lote_;
    private javax.swing.JMenuItem Aplicar_Otsu_Imagem_;
    private javax.swing.JMenuItem Aplicar_Otsu_Lote_;
    private javax.swing.JMenu Binarizacao_Fuzzy_Huang_;
    private javax.swing.JMenu Binarizacao_Otsu_;
    private javax.swing.JMenuItem Carregar_Imagem_;
    private javax.swing.JMenu Menu_Arquivo_;
    private javax.swing.JMenu Menu_Outros_;
    private javax.swing.JMenu Menu_Segmentacao_;
    private javax.swing.JMenu Menu_Skin_Detection_;
    private javax.swing.JMenuBar Menus;
    private javax.swing.JMenuItem Sair_;
    private javax.swing.JMenuItem Salvar_;
    private javax.swing.JMenuItem Sobre_;
    private javax.swing.JPopupMenu.Separator ___Separador_01;
    private javax.swing.JPopupMenu.Separator ___Separador_03;
    private javax.swing.JPopupMenu.Separator ___Separador_04;
    private javax.swing.JPopupMenu.Separator ___Separador_07;
    private javax.swing.JPopupMenu.Separator ___Separador_08;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
